#!/bin/bash
FF_DIR='/home/vagrant/ffxi'
cd $FF_DIR/

echo "Starting Servers ..."
sudo -H -u vagrant /usr/bin/screen -dmS lobby $FF_DIR/dsconnect
sudo -H -u vagrant /usr/bin/screen -dmS game $FF_DIR/dsgame
sudo -H -u vagrant /usr/bin/screen -dmS search $FF_DIR/dssearch
sleep 1
screen -ls
